### ISSUE TITLE
Consider turning this into a more general purpose keybindings manager

### ISSUE THREAD

**Issue by jody-frankowski** [oblitum/caps2esc#7]
First of all, thank you for this tool :heart:.

Considering the usefulness of this tool, would you consider extending it in a more general purpose rebindings manager?

The following features make this tool stand out for me:
* TTY support
* Re-plugging keyboards is transparent

Another approach would be to have an extensive documentation on how to add your rebindings.

**Comment by oblitum** [comment]
Hi @jody-frankowski, glad you liked it. The thing is that a set of tools almost finished in my machine for this purpose but I've stopped development for the moment because of other urgent matters. But they are coming as soon as I finish this.

Notice that this is a duplicated of #4, [where I mention the design of the general tool](https://github.com/oblitum/caps2esc/issues/4#issuecomment-262005338), hence I'm closing this one.

**Comment by oblitum** [comment]
Hi @jody-frankowski, glad you liked it. The thing is that I have a set of tools almost finished in my machine for this purpose but I've stopped development for the moment because of other urgent matters. But they are coming as soon as I finish this.

Notice that this is a duplicated of #4, [where I mention the design of the general tool](https://github.com/oblitum/caps2esc/issues/4#issuecomment-262005338), hence I'm closing this one.
